---

- name: Install acl package
  apt:
    name: acl
    state: latest

- name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
  shell: |
    swapoff -a

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Create containerd config file
  file:
    path: "/etc/modules-load.d/k8s.conf"
    state: "touch"

- name: Add conf for containerd
  blockinfile:
    path: "/etc/modules-load.d/k8s.conf"
    block: |
          overlay
          br_netfilter

# - name: Create containerd config file
#   file:
#     path: "/etc/modules-load.d/containerd.conf"
#     state: "touch"

# - name: Add conf for containerd
#   blockinfile:
#     path: "/etc/modules-load.d/containerd.conf"
#     block: |
#           overlay
#           br_netfilter

- name: modprobe
  shell: |
          sudo modprobe overlay
          sudo modprobe br_netfilter

- name: Set system configurations for Kubernetes networking
  file:
    path: "/etc/sysctl.d/k8s.conf"
    state: "touch"

- name: Add conf for containerd
  blockinfile:
    path: "/etc/sysctl.d/k8s.conf"
    block: |
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-ip6tables = 1

# - name: Set system configurations for Kubernetes networking
#   file:
#     path: "/etc/sysctl.d/99-kubernetes-cri.conf"
#     state: "touch"

# - name: Add conf for containerd
#   blockinfile:
#     path: "/etc/sysctl.d/99-kubernetes-cri.conf"
#     block: |
#           net.bridge.bridge-nf-call-iptables = 1
#           net.ipv4.ip_forward = 1
#           net.bridge.bridge-nf-call-ip6tables = 1

- name: Apply new settings
  command: sudo sysctl --system

- name: install and set config containerd
  shell: |
          sudo apt-get update && sudo apt-get install -y containerd
          sudo mkdir -p /etc/containerd
          sudo containerd config default | sudo tee /etc/containerd/config.toml

- name: change SystemdCgroup field to true
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'


- name: Restart containerd
  command: sudo systemctl restart containerd

- name: install and configure dependencies
  shell: |
          sudo apt-get update && sudo apt-get install -y apt-transport-https curl
          sudo rm -f /etc/apt/keyrings/kubernetes-apt-keyring.gpg
          curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg


- name: Create kubernetes repo file
  file:
    path: "/etc/apt/sources.list.d/kubernetes.list"
    state: "touch"

- name: Add K8s Source
  blockinfile:
    path: "/etc/apt/sources.list.d/kubernetes.list"
    block: |
          deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /

- name: install kubernetes
  shell: |
          sudo apt-get update
          sudo apt-get install -y kubelet kubeadm kubectl
          sudo apt-mark hold kubelet kubeadm kubectl

- name: enable kubelet before kubeadm
  become: true
  shell: systemctl enable --now kubelet