masters:
  hosts:
    master:
      ansible_host: 192.168.0.206
      ansible_user: admin
workers:
  hosts:
    worker01:
      ansible_host: 192.168.0.203
      ansible_user: admin
    worker02:
      ansible_host: 192.168.0.204
      ansible_user: admin
    worker03:
      ansible_host: 192.168.0.205
      ansible_user: admin