version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: always
    expose: 
      - 27017
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - /data/dbs/mongodb:/data/db
  mariadb:
    image: mariadb:latest
    expose: 
      - 3306
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: admin
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_PASSWORD: admin
    volumes:
      - /data/dbs/mariadb:/var/lib/mysql